In [2]:
#Week 2

In [7]:
#Numpy
import numpy as np

numArr = np.array([1,2,3,4,5,6,7,8,9])
print(numArr.shape) # 9 row 0 column - 9,0

(9,)


In [14]:
reShapedNumArr = numArr.reshape(3,3)
print(reShapedNumArr)
#array size and new shape size must be the same 3*3 = 9

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print("dimesion = ", reShapedNumArr.ndim) #gives the matrix size
print("array data type = ", reShapedNumArr.dtype) #returns the type of data inside the array
print("array count = ", reShapedNumArr.size) # gives array count, size

dimesion =  2
array data type =  int64
array count =  9


In [28]:
zeros = np.zeros((4,3)) #allocates default size for array, filled with 0
print(zeros)
print("----")
print(np.ones((3,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
a = np.linspace(0,10,20) #20 numbers between 0 and 10 are printed.
print(a)
intArr = np.linspace(0,10,20,dtype=float) #dtype never be an int

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [40]:
list = [1,2,3,4] # it will be list
arr = np.array([5,6,7,8]) # array

print(list)
print(arr)
print(np.array(list)) # convert list to array
print(list(arr)) # convert array to list

[1, 2, 3, 4]
[5 6 7 8]
[1 2 3 4]


In [44]:
newArr = np.array([1,2,3,4])
testArr = newArr
test2Arr = newArr
newArr[1] = 0
print(newArr)
print(testArr)
print(test2Arr)


newList = [1,2,3]
testList = newList
newList[0] = 0
print(newList)
print(testList)

#np.array is a reference type not a value type
# list is reference type either :/

[1 0 3 4]
[1 0 3 4]
[1 0 3 4]
[0, 2, 3]
[0, 2, 3]


In [47]:
arr =  np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("----")
print(arr[::-1]) #inverts the outer array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----
[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [51]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
print("----")
print(x[1,1])
print("----")
print(x[:,1])
print("----")
print(x[1,:])
print("----")
print(x[1,1:4])
print("----")
print(x[-1,:]) # last row, all column
print("----")
print(x[:,-1]) # last column, all row
#x[row, column]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----
6
----
[ 2  6 10]
----
[5 6 7 8]
----
[6 7 8]
----
[ 9 10 11 12]
----
[ 4  8 12]


In [57]:
print(x.ravel())
print(x.reshape(1,x.size))
arrayTranspose = x.T
print(arrayTranspose) #transpose the array.

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [67]:
arr20 = np.array([[1,2,3],[4,5,6]])
print(arr20)
arr20.resize((3,2))
print(arr20) #resize modifies the array itself, unlike reshape

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
